# Generated by Django 6.0.1 on 2026-01-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_excel', models.IntegerField(null=True)),
                ('programa', models.CharField(max_length=500)),
                ('area_responsable', models.CharField(max_length=255, null=True)),
                ('presupuesto_modificado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('anteproyecto_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avance_fisico_pct', models.FloatField(default=0)),
                ('avance_financiero_pct', models.FloatField(default=0)),
                ('urgencia', models.IntegerField(default=1)),
                ('impacto_social', models.IntegerField(default=1)),
                ('riesgo_nivel', models.IntegerField(default=1)),
                ('viabilidad_ejecucion', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
