# Generated by Django 6.0.1 on 2026-01-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='fecha_inicio',
            new_name='fecha_inicio_prog',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='fecha_termino',
            new_name='fecha_inicio_real',
        ),
        migrations.AddField(
            model_name='obra',
            name='alineacion_estrategica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obra',
            name='beneficio_ciudadania',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='complejidad_tecnica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obra',
            name='costo_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obra',
            name='eje_institucional',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_termino_prog',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_termino_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='problema_resuelve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='proyecto_2025',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obra',
            name='recursos_disponibles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obra',
            name='semaforo_calculado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='solucion_ofrece',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='anteproyecto_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='obra',
            name='presupuesto_modificado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='obra',
            name='programa',
            field=models.TextField(null=True),
        ),
    ]
