# Generated by Django 6.0.1 on 2026-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0002_rename_fecha_inicio_obra_fecha_inicio_prog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='proyecto_2025',
            new_name='meta_2025',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='semaforo_calculado',
        ),
        migrations.AddField(
            model_name='obra',
            name='acciones_correctivas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='alcaldias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='alcance_territorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='alineacion_gobierno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='beneficiarios_directos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='capitulo_gasto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='concentrado_programas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='contratista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='control_captura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='control_notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='dato_destacable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='dependencias_nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obra',
            name='duracion_meses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='estatus_general',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='estatus_permisos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='estrategia_comunicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='etapa_desarrollo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fuente_financiamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='hitos_comunicacionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='impacto_social_nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obra',
            name='mensajes_clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='meta_2026',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obra',
            name='multianualidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='permisos_requeridos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='poblacion_objetivo_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='poblacion_perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='problemas_identificados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='proyecto_2025_presupuesto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='puntuacion_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='relevancia_comunicacional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='requisitos_especificos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='responsable_operativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_recurso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='ubicacion_especifica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='ultima_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='viabilidad_administrativa_semaforo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='viabilidad_juridica_semaforo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='viabilidad_presupuestal_semaforo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='viabilidad_tecnica_semaforo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='viabilidad_temporal_semaforo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='area_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='eje_institucional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='programa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
